import { PrismaClient } from "@/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { stripSslMode } from "@/lib/db-url";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

// POSTGRES_PRISMA_URL is what Vercel's Supabase marketplace integration
// auto-provisions (already pooled + formatted for Prisma) — preferred
// since it's generated by the integration itself, not hand-typed.
// DATABASE_URL is the fallback for projects without that integration.
const rawConnectionString = process.env.POSTGRES_PRISMA_URL ?? process.env.DATABASE_URL;

if (!rawConnectionString) {
  throw new Error(
    "Neither POSTGRES_PRISMA_URL nor DATABASE_URL is set. If the Supabase Vercel " +
      "integration is connected, POSTGRES_PRISMA_URL should already exist — run " +
      "`vercel env pull .env`. Otherwise set DATABASE_URL to Supabase's pooled " +
      "connection string (see .env.example)."
  );
}

// node-postgres (unlike Prisma's own migrate engine, which has its own TLS
// stack) needs SSL passed explicitly here — see src/lib/db-url.ts for why
// `sslmode` must be stripped from the connection string for our explicit
// `ssl` option to actually take effect.
const adapter = new PrismaPg({
  connectionString: stripSslMode(rawConnectionString),
  ssl: { rejectUnauthorized: false },
});

export const prisma = globalForPrisma.prisma ?? new PrismaClient({ adapter });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
